# Generated by Django 3.0 on 2019-12-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='learning_logs/documents/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Entry')),
            ],
        ),
    ]
