# Generated by Django 3.0 on 2019-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20191227_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sub',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
