# Generated by Django 3.0 on 2019-12-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20191227_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
